routes/web.php
<?php


Route::get('/', function () {
    return view('welcome');
});

Route::prefix('admin')->group(function (){
    Auth::routes();

    Route::group(['prefix' => 'users', 'as' => 'admin.users.'], function(){

        Route::name('settings.edit')->get('settings', 'Admin\UserSettingsController@edit');
        Route::name('settings.update')->put('update', 'Admin\UserSettingsController@update');        
    });


    Route::group([

        'namespace' => 'Admin\\',
        'as' => 'admin.',
        'middleware' => ['auth', 'can:admin']

    ], function (){

        Route::name('dashboard')->get('/dashboard', function () {
            return "Estou no Dashbaord";
        });   

        Route::group(['prefix' => 'users', 'as' => 'users.'], function (){
           Route::name('show_details')->get('show_details', 'UsersController@showDetails'); 
           Route::group(['prefix' => '/{user}/profile'], function() {
                Route::name('profile.edit')->get('', 'UserProfileController@edit');
                Route::name('profile.update')->put('', 'UserProfileController@update');
           });
        });

        Route::resource('users', 'UsersController');
        Route::resource('subjects', 'SubjectsController'); //disciplinas
        Route::resource('class_informations', 'ClassInformationsController'); //turmas



/***************************************************************************************************************/
        // Teste geração PDF com barryvdh-DOMpdf
        // Route::get('users-testepdf', function() {
        //     $pdf = \PDF::LoadView('user-teste-pdf', ['users' => \SON\Models\User::all()]);
        //     return $pdf->stream();

        //     // return view('user-teste-pdf', ['users' => \SON\Models\User::all()]);
        // }); 


        // Teste geração de PDF com snappy (wktohtmlpdf)
        Route::get('users-testepdf', function() {
            $pdf = \PDF::LoadView('user-teste-pdf', ['users' => \SON\Models\User::all()]);
            return $pdf->inline();
        });


    });

/*******************************************************************************************************************/
});

//Auth::routes();

Route::get('/admin', 'HomeController@index')->name('admin');

// Testando biblioteca pdf
Route::get('/testepdf', function() {
    $pdf = \PDF::loadHTML('<h1>TestePDF</h1>');

    //Abre em uma nova aba do navegador
    // return $pdf->stream(); 

    //Faz o download do arquivo
    $pdf->save(storage_path('app\meupdf2.pdf'));
    return $pdf->download('meupdf.pdf'); 
    
});
//teste

// Route::get('/teste', function() {
//     // return DB::table('users')->get();

//     $nome = "Leonardo";
//     $sobreNome = "vales";
//     $idade = "26";

//     $dados = [

//         'NomeL' => $nome,
//         'sobreNomeL' => $sobreNome,
//         'idadeL' => $idade,

//     ];

//     foreach ($dados as $key => $dado) {

//         if ($key == 'idadeL') 
//             $idade_oficial = $dado;
//         else if ($key == 'sobreNomeL')
//             $sobreNome_oficial = $dado;

//     }

//     echo $idade_oficial;
//     echo $sobreNome_oficial;    

// });

app/Models/User.php
<?php

namespace SON\Models;

use Bootstrapper\Interfaces\TableInterface;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
Use SON\Notifications\UserCreated;
Use SON\Models\UserProfile;

class User extends Authenticatable implements TableInterface
{
    use Notifiable;
    const ROLE_ADMIN = 1;
    const ROLE_TEACHER = 2;
    const ROLE_STUDENT = 3;


    protected $fillable = [
        'name', 
        'email', 
        'password',
        'enrolment'
    ];


    protected $hidden = [
        'password', 'remember_token',
    ];

    public function profile()
    {
        return $this->hasOne(UserProfile::class)->withDefault(); //Este método analisa se o campo existe. Caso exista, retorna a instância do profile para que seja salvo. Se não existir, ele retorna uma instância vazia do profile para que possa ser criado.. hasOne = cada usuário terá apenas um perfil
    }

    public function userable()
    {
        return $this->morphTo();
    }

    public static function createFully($data)
    {
        $password         = str_random(6);
        $data['password'] = $password;
        $user = parent::create($data+['enrolment' => str_random(6)]);
        self::assignEnrolment($user, self::ROLE_ADMIN);
        self::assignRole($user, $data['type']);
        $user->save();

        if (isset($data['send_mail'])) {
            $token = \Password::broker()->createToken($user);
            $user->notify(new UserCreated($token));
        }

        return compact('user', 'password');
    }

    public static function assignEnrolment(User $user,$type)
    {
        $types = [
            self::ROLE_ADMIN => 100000,
            self::ROLE_TEACHER => 400000,
            self::ROLE_STUDENT => 700000,
        ];

        $user->enrolment = $types[$type] + $user->id;
        return $user->enrolment;
    }

    public function getTableHeaders()
    {
        return ['ID', 'Nome', 'E-mail'];
    }

    public function getValueForHeader($header)
    {
        switch($header)
        {
            case 'ID':
                return $this->id;
            case 'Nome':
                return $this->name;
            case 'E-mail':
                return $this->email;
        }
    }

    public static function assignRole(User $user, $type)
    {
        $types = [
            self::ROLE_ADMIN => Admin::class,
            self::ROLE_TEACHER => Teacher::class,
            self::ROLE_STUDENT => Student::class,
        ];        

        $model = $types[$type];
        $model = $model::create([]);
        $user->userable()->associate($model);
    }

}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace SON\Http\Controllers\Admin;

use Kris\LaravelFormBuilder\Form;
use SON\Forms\UserForm;
use SON\Models\User;
use Illuminate\Http\Request;
use SON\Http\Controllers\Controller;

class UsersController extends Controller
{
    public function index()
    {
        $users = User::paginate();
        return view('admin.users.index', compact('users'));
    }

    public function create()
    {
        $form = \FormBuilder::create(UserForm::class, [
            'url' => route('admin.users.store'),
            'method' => 'POST'
        ]);

        return view('admin.users.create', compact('form'));
    }

    public function store(Request $request)
    {
        $form = \FormBuilder::create(UserForm::class); 

        if (!$form->isValid()) {
            return redirect()->back()
                             ->withErrors($form->getErrors())  
                             ->withInput(); 
        }

        $data             = $form->getFieldValues();

        $result = User::createFully($data);
        $request->session()->flash('message','Usuário criado com sucesso!');
        $request->session()->flash('user_created',[
            'id' => $result['user']->id,
            'password' => $result['password']
        ]);

        return redirect()->route('admin.users.show_details');
    }

    public function showDetails()
    {
        $userData       = session('user_created');
        $user           = User::findOrFail($userData['id']);
        $user->password = $userData['password'];
        return view('admin.users.show_details', compact('user'));
    }

    public function show(User $user)
    {
        return view('admin.users.show', compact('user'));
    }

    public function edit(User $user)
    {
        $form = \FormBuilder::create(UserForm::class, [
            'url' => route('admin.users.update',['user' => $user->id]),
            'method' => 'PUT',
            'model' => $user
        ]);   

        return view('admin.users.edit', compact('form'));     
    }

    public function update(User $user)
    {
        $form = \FormBuilder::create(UserForm::class, [
            'data' => ['id' => $user->id]
        ]); 

        if (!$form->isValid()) {
            return redirect()->back()
                             ->withErrors($form->getErrors())  
                             ->withInput(); 
        } 

        $data = $form->getFieldValues();
        $user->update($data);  
        session()->flash('message','Usuário editado com sucesso!');
        return redirect()->route('admin.users.index');           
    }

    public function destroy(User $user)
    {
        $user->delete();
        session()->flash('message','Usuário excluído com sucesso!');
        return redirect()->route('admin.users.index');
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <h3>Novo Usuário</h3>
            {!!form($form->add('insert','submit', [
                'attr' => ['class' => 'btn btn-primary btn-block'],
                'label' => Icon::create('floppy-disk').' Inserir'
            ]))!!}        
        </div>   
    </div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">

            @component('admin.users.tabs-component', ['user' => $form->getModel()])

                <h3>Editar Usuário</h3>
                {!!form($form->add('edit','submit', [
                    'attr' => ['class' => 'btn btn-primary btn-block'],
                    'label' => Icon::create('floppy-disk').' Editar'
                ]))!!} 

            @endcomponent
       
        </div>   
    </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <div class="row">
            <h3>Listagem de usuários</h3>
            {!! Button::primary(Icon::plus().' Novo Usuário')->asLinkTo(route('admin.users.create')) !!}       
        </div>  
        <div class="row">
            {!! 
                Table::withContents($users->items())->striped()
                                                    ->callback('Ações', function($field, $model){
                    $linkEdit   = route('admin.users.edit',['user' => $model->id]);
                    $linkDelete = route('admin.users.destroy',['user' => $model->id]);
                    $linkShow   = route('admin.users.show',['user' => $model->id]);
                    return Button::warning(Icon::create('pencil').' Editar')->asLinkTo($linkEdit).'  '.
                           Button::danger(Icon::create('trash').' Deletar')->asLinkTo($linkDelete).'  '.
                           Button::success(Icon::create('eye-open').' Ver')->asLinkTo($linkShow);
                }) 
            !!}
        </div> 

        {!! $users->links() !!}
    </div>
@endsection

resources/views/admin/users/settings.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <h3>Editar meu perfil de usuário</h3>
            {!!form($form->add('insert','submit', [
                'attr' => ['class' => 'btn btn-primary btn-block'],
                'label' => Icon::create('floppy-disk').' Salvar'
            ]))!!}        
        </div>   
    </div>
@endsection

resources/views/admin/users/show.blade.php
@extends('layouts.app');

@section('content')

    <div class="container">
        <div class="row">
            <h1>Ver Usuário</h1>

            @php
                $linkEdit = route('admin.users.edit',['user' => $user->id]);
                $linkDelete = route('admin.users.destroy',['user' => $user->id]);
            @endphp    

            {!! Button::primary(Icon::pencil().' Editar')->asLinkTo($linkEdit) !!}
            {!! 
                Button::danger(Icon::trash().' Excluir')->asLinkTo($linkDelete)
                    ->addAttributes([
                        'onclick' => "event.preventDefault();document.getElementById(\"form-delete\").submit();"
                    ]) 
            !!}
            @php
                $formDelete = FormBuilder::plain([
                    'id' => 'form-delete',
                    'url' => $linkDelete,
                    'method' => 'DELETE',
                    'style' => 'display:none'
                ]);
            @endphp  
            {!! form($formDelete) !!}
            <br/><br/>
            <table class="table table-bordered">
            <tbody>
                <tr>
                    <th scope="row">ID</th>
                    <td>{{$user->id}}</td>
                </tr>
                <tr>
                    <th scope="row">Nome</th>
                    <td>{{$user->name}}</td>
                </tr>
                <tr>
                    <th scope="row">E-mail</th>
                    <td>{{$user->email}}</td>
                </tr>                                
            </tbody>

            </table>

        </div>
    </div>



@endsection

resources/views/admin/users/show_details.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <h3>Usuário - {{$user->name}}</h3>
            {!! Button
                    ::normal('Listar usuários')
                    ->appendIcon(Icon::thList())
                    ->asLinkTo(route('admin.users.index'))
                    ->addAttributes([
                        'class' => 'hidden-print'
                    ])
            !!}
            <br/><br/>
            <table class="table table-bordered">
                <tbody>
                <tr>
                    <th scope="row">#</th>
                    <td>{{$user->id}}</td>
                </tr>
                <tr>
                    <th scope="row">Nome</th>
                    <td>{{$user->name}}</td>
                </tr>
                <tr>
                    <th scope="row">E-mail</th>
                    <td>{{$user->email}}</td>
                </tr>
                <tr>
                    <th scope="row">Password</th>
                    <td>{!! Badge::withContents($user->password)!!}</td>
                </tr>
                </tbody>
            </table>

        </div>
    </div>
@endsection

resources/views/admin/users/tabs-component.blade.php
@php
    $tabs = [
       ['title' => 'Informações','link' => route('admin.users.edit',['user' => $user->id])],
       ['title' => 'Perfil','link' => route('admin.users.profile.edit',['user' => $user->id])],
    ]
@endphp


<h3>Gerenciar usuário</h3>

<div class="text-right">
    {!! Button::link('Listar usuários')->asLinkTo(route('admin.users.index')) !!}
</div>

{!! Navigation::tabs($tabs) !!}

<div>
     {!! $slot !!}
</div>