routes/web.php
<?php


Route::get('/', function () {
    return view('welcome');
});

Route::prefix('admin')->group(function (){
    Auth::routes();

    Route::group(['prefix' => 'users', 'as' => 'admin.users.'], function(){

        Route::name('settings.edit')->get('settings', 'Admin\UserSettingsController@edit');
        Route::name('settings.update')->put('update', 'Admin\UserSettingsController@update');        
    });


    Route::group([

        'namespace' => 'Admin\\',
        'as' => 'admin.',
        'middleware' => ['auth', 'can:admin']

    ], function (){

        Route::name('dashboard')->get('/dashboard', function () {
            return "Estou no Dashbaord";
        });   

        Route::group(['prefix' => 'users', 'as' => 'users.'], function (){
           Route::name('show_details')->get('show_details', 'UsersController@showDetails'); 
           Route::group(['prefix' => '/{user}/profile'], function() {
                Route::name('profile.edit')->get('', 'UserProfileController@edit');
                Route::name('profile.update')->put('', 'UserProfileController@update');
           });
        });

        Route::resource('users', 'UsersController');
        Route::resource('subjects', 'SubjectsController'); //disciplinas
        Route::resource('class_informations', 'ClassInformationsController'); //turmas



/***************************************************************************************************************/
        // Teste geração PDF com barryvdh-DOMpdf
        // Route::get('users-testepdf', function() {
        //     $pdf = \PDF::LoadView('user-teste-pdf', ['users' => \SON\Models\User::all()]);
        //     return $pdf->stream();

        //     // return view('user-teste-pdf', ['users' => \SON\Models\User::all()]);
        // }); 


        // Teste geração de PDF com snappy (wktohtmlpdf)
        Route::get('users-testepdf', function() {
            $pdf = \PDF::LoadView('user-teste-pdf', ['users' => \SON\Models\User::all()]);
            return $pdf->inline();
        });


    });

/*******************************************************************************************************************/
});

//Auth::routes();

Route::get('/admin', 'HomeController@index')->name('admin');

// Testando biblioteca pdf
Route::get('/testepdf', function() {
    $pdf = \PDF::loadHTML('<h1>TestePDF</h1>');

    //Abre em uma nova aba do navegador
    // return $pdf->stream(); 

    //Faz o download do arquivo
    $pdf->save(storage_path('app\meupdf2.pdf'));
    return $pdf->download('meupdf.pdf'); 
    
});
//teste

// Route::get('/teste', function() {
//     // return DB::table('users')->get();

//     $nome = "Leonardo";
//     $sobreNome = "vales";
//     $idade = "26";

//     $dados = [

//         'NomeL' => $nome,
//         'sobreNomeL' => $sobreNome,
//         'idadeL' => $idade,

//     ];

//     foreach ($dados as $key => $dado) {

//         if ($key == 'idadeL') 
//             $idade_oficial = $dado;
//         else if ($key == 'sobreNomeL')
//             $sobreNome_oficial = $dado;

//     }

//     echo $idade_oficial;
//     echo $sobreNome_oficial;    

// });

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <style type="text/css">
        @media print{
            .hidden-print {
                display: none !important;
            }
        }
    </style>
</head>
<body>
    <div id="app">
        
        @php
            $navbar = Navbar::withBrand(config('app.name'), route('admin.dashboard'))->inverse();
            if(Auth::check()){

                if(Gate::allows('admin')){
                    $arrayLinks = [
                        ['link' => route('admin.users.index'), 'title' => 'Usuários'],
                        ['link' => route('admin.subjects.index'), 'title' => 'Disciplina'],
                        ['link' => route('admin.class_informations.index'), 'title' => 'Turma']
                        
                    ];
                    $navbar->withContent(Navigation::links($arrayLinks));
                }

                $arrayLinksRight =[
                    [
                        Auth::user()->name,
                        [
                            [
                                'link' => route('admin.users.settings.edit'),
                                'title' => 'Configurações'
                            ],
                            [
                                'link' => route('logout'),
                                'title' => 'Logout',
                                'linkAttributes' => [
                                    'onclick' => "event.preventDefault();document.getElementById(\"form-logout\").submit();"
                                ]
                            ]
                        ]
                    ]
                ];

                $navbar->withContent(Navigation::links($arrayLinksRight)->right());

                $formLogout = FormBuilder::plain([
                    'id' => 'form-logout',
                    'url' => route('logout'),
                    'method' => 'POST',
                    'style' => 'display:none'
                ]);
            }
        @endphp

        {!! $navbar !!}
        
        @if(Auth::check())
            {!! form($formLogout) !!}
        @endif

        @if (Session::has('message'))
            <div class="container hidden-print">
                {!! Alert::success(Session::get('message'))->close() !!}
            </div>
        @endif

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>